<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Reaparr.Identity.Contracts</AssemblyName>
        <RootNamespace>Reaparr.Identity.Contracts</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Data.Contracts\Data.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Reaparr.Data.Contracts" />
    </ItemGroup>
</Project>
