<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Reaparr.Environment</AssemblyName>
        <RootNamespace>Reaparr.Environment</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.1.0" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Xdg.Directories" Version="0.1.2" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Reaparr.BaseTests" />
        <InternalsVisibleTo Include="Reaparr.Environment.UnitTests" />
    </ItemGroup>
</Project>
