<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Reaparr.Domain</RootNamespace>
        <AssemblyName>Reaparr.Domain</AssemblyName>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="ByteSize" Version="2.1.2" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.1.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FastEndpoints" Version="7.0.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.0" />
        <PackageReference Include="NaturalSort.Extension" Version="4.3.0" />
        <PackageReference Include="PasswordGenerator" Version="2.1.0" />
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
        <PackageReference Include="System.Reactive" Version="6.0.1" />
        <PackageReference Include="System.Text.Json" Version="9.0.8" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\FluentResultExtensions\FluentResultExtensions.csproj" />
    </ItemGroup>
</Project>
