<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.Data.UnitTests</RootNamespace>
        <AssemblyName>Reaparr.Data.UnitTests</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.24.0" />
        <PackageReference Include="coverlet.collector" Version="8.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Data\Data.csproj" />
        <ProjectReference Include="..\..\BaseTests\BaseTests.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Microsoft.EntityFrameworkCore" />
        <Using Include="Reaparr.Data.Contracts" />
    </ItemGroup>
</Project>
