<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Reaparr.PublicAPI</AssemblyName>
        <RootNamespace>Reaparr.PublicAPI</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.1.0" />
        <PackageReference Include="BencodeNET" Version="5.0.0" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FastEndpoints" Version="8.1.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Data.Contracts\Data.Contracts.csproj" />
        <ProjectReference Include="..\Identity.Contracts\Identity.Contracts.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\PublicAPI.Contracts\PublicAPI.Contracts.csproj" />
        <ProjectReference Include="..\Settings.Contracts\Settings.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="System.ComponentModel.DataAnnotations" />
        <Using Include="System.ComponentModel.DataAnnotations.Schema" />
        <Using Include="FastEndpoints" />
        <Using Include="Reaparr.FluentResults" />
        <Using Include="FluentValidation" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.EntityFrameworkCore" />
        <Using Include="Reaparr.Data.Contracts" />
        <Using Include="Reaparr.Domain" />
        <Using Include="Reaparr.FluentResultExtensions" />
        <Using Include="Reaparr.Identity.Contracts" />
        <Using Include="Reaparr.Logging" />
        <Using Include="Reaparr.PublicAPI.Contracts" />
        <Using Include="Reaparr.Settings.Contracts" />
        <Using Include="Serilog" />
    </ItemGroup>
</Project>
