<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Reaparr.PublicAPI</AssemblyName>
        <RootNamespace>Reaparr.PublicAPI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="8.4.0" />
        <PackageReference Include="BencodeNET" Version="5.0.0" />
        <PackageReference Include="FastEndpoints" Version="7.0.1" />
    </ItemGroup>
        <ItemGroup>
      <ProjectReference Include="..\Data.Contracts\Data.Contracts.csproj" />
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Settings.Contracts\Settings.Contracts.csproj" />
    </ItemGroup>
        <ItemGroup>
          <Compile Include="..\Domain\GlobalUsings.cs">
            <Link>GlobalUsings.cs</Link>
          </Compile>
        </ItemGroup>

</Project>
