name: 'Dotnet Setup'
description: 'Setup .NET, restore dependencies and build'
inputs:
    project-path:
        description: 'Relative path to the project or solution to build'
        required: true
runs:
    using: 'composite'
    steps:
        -   name: Setup .NET SDK
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 9.x.x
                cache: true
                cache-dependency-path: |
                    **/*.csproj
                    **/global.json

        -   name: Restore dependencies
            shell: bash
            run: dotnet restore ${{ inputs.project-path }} --locked-mode

        -   name: Build
            shell: bash
            run: dotnet build ${{ inputs.project-path }} --no-restore
