<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>Reaparr.FileSystem</AssemblyName>
        <RootNamespace>Reaparr.FileSystem</RootNamespace>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
        <ProjectReference Include="..\Data.Contracts\Data.Contracts.csproj" />
        <ProjectReference Include="..\FileSystem.Contracts\FileSystem.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.0.0" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Jason.Landbridge.Autofac.Extras.Quartz" Version="9.0.3" />
        <PackageReference Include="System.IO.Abstractions" Version="22.1.0" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Domain\GlobalUsings.cs" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="_Shared\" />
    </ItemGroup>
</Project>
