<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>PlexRipper.FileSystem</AssemblyName>
        <RootNamespace>PlexRipper.FileSystem</RootNamespace>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
        <ProjectReference Include="..\Data.Contracts\Data.Contracts.csproj" />
        <ProjectReference Include="..\FileSystem.Contracts\FileSystem.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" Version="8.4.0" />
        <PackageReference Include="Autofac.Extras.Quartz" Version="10.0.0" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.1.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.IO.Abstractions" Version="22.0.15" />
        <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Domain\GlobalUsings.cs" />
    </ItemGroup>
</Project>
