<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Reaparr.FileSystem</AssemblyName>
        <RootNamespace>Reaparr.FileSystem</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
        <ProjectReference Include="..\Data.Contracts\Data.Contracts.csproj" />
        <ProjectReference Include="..\FileSystem.Contracts\FileSystem.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.1.0" />
        <PackageReference Include="Autofac.Extras.Quartz" Version="11.0.0" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.IO.Abstractions" Version="22.1.0" />
    </ItemGroup>
    <ItemGroup></ItemGroup>
    <ItemGroup>
        <Folder Include="_Shared\" />
    </ItemGroup>
</Project>
