export enum DialogType {
	AddConnectionDialog = 'add-connection-dialog',
	AccountConfirmationDialog = 'account-confirmation-dialog',
	AccountDialog = 'account-dialog',
	AccountTokenValidateDialog = 'account-token-validate-dialog',
	AccountGenerateTokenDialog = 'account-generate-token-dialog',
	AccountVerificationCodeDialog = 'account-verification-code-dialog',
	AlertInfoDialog = 'alert-info-dialog',
	CheckServerConnectionDialogName = 'check-server-connection-dialog',
	DirectoryBrowserDialog = 'directory-browser-dialog',
	DiscordServerInviteDialog = 'discord-server-invite-dialog',
	DownloadDetailsDialog = 'download-details-dialog',
	FirstTimeSetupDialog = 'first-time-setup-dialog',
	HelpInfoDialog = 'help-info-dialog',
	MediaDownloadConfirmationDialog = 'media-download-confirmation-dialog',
	MediaSelectionDialog = 'media-selection-dialog',
	MediaOptionsDialog = 'media-options-dialog',
	ResetDatabaseConfirmationDialog = 'reset-database-confirmation-dialog',
	ServerHideConfirmationDialog = 'server-hide-confirmation-dialog',
	ServerSettingsDialog = 'server-settings-dialog',
	SetupSkipConfirmationDialog = 'setup-skip-confirmation-dialog',
	SyncServerMediaDialog = 'sync-server-media-dialog',
}
