<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <PackageId>IntegrationTests</PackageId>
        <RootNamespace>Reaparr.IntegrationTests</RootNamespace>
        <AssemblyName>Reaparr.IntegrationTests</AssemblyName>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.45.29" />
        <PackageReference Include="coverlet.collector" Version="8.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\BaseTests\BaseTests.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Application\PlexAccounts\Create\" />
        <Folder Include="FileSystem" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Microsoft.EntityFrameworkCore" />
        <Using Include="Reaparr.Application" />
        <Using Include="Reaparr.Application.Contracts" />
        <Using Include="Reaparr.Data.Contracts" />
        <Using Include="Reaparr.Environment" />
        <Using Include="Reaparr.FluentResultExtensions" />
        <Using Include="System.Net" />
    </ItemGroup>
</Project>
