namespace Reaparr.Domain;

public abstract class BasePlexMediaData : BasePlexMediaQuality
{
    /// <summary>
    /// Plex Media.id.
    /// Immutable identifier for the physical media file.
    /// Used as the primary file identity for incremental sync.
    /// </summary>
    [Column(Order = 1)]
    public required long PlexMediaId { get; init; }

    /// <summary>
    /// Plex Part.id.
    /// Immutable identifier for the physical media file.
    /// Used as the primary file identity for incremental sync.
    /// </summary>
    [Column(Order = 2)]
    public required long PlexPartId { get; init; }

    /// <summary>
    /// Plex Metadata.ratingKey.
    /// Identifies the logical media item (movie / episode) this file belongs to.
    /// <example>"23920"</example>
    /// </summary>
    [Column(Order = 3)]
    public required int RatingKey { get; init; }

    /// <summary>
    /// Plex-generated key used to access this specific part.
    /// <example>"/library/parts/47140/1712273142/file.mkv"</example>
    /// </summary>
    [Column(Order = 4)]
    public required string Key { get; init; }

    /// <summary>
    /// Duration of the media file in milliseconds.
    /// </summary>
    [Column(Order = 5)]
    public required int Duration { get; init; }

    /// <summary>
    /// The original filename of the media file as reported by Plex.
    /// </summary>
    [Column(Order = 6)]
    public required string OriginalFilename { get; init; }

    /// <summary>
    /// The filename of the media file as generated by Reaparr.
    /// NOTE: This is done because Sonarr/Radarr parse their media specs from this name
    /// </summary>
    [Column(Order = 7)]
    public string? GeneratedFilename { get; set; }

    /// <summary>
    /// File size in bytes.
    /// </summary>
    [Column(Order = 8)]
    public required long Size { get; init; }

    /// <summary>
    /// Container format of the file (e.g. mkv, mp4, mpeg).
    /// </summary>
    [Column(Order = 9)]
    public required string Container { get; init; }

    /// <summary>
    /// If the <see cref="OriginalFilename"/> is not a valid name for the purposes of Sonarr/Radarr parsing. Then it requires an additional metadata call to get more media specs in order to generate a better name
    /// </summary>
    [Column(Order = 10)]
    public bool NeedsGeneratedName { get; set; }

    /// <summary>
    /// Timestamp of the last metadata update in Plex.
    /// Used to determine whether enrichment or resync is required.
    /// </summary>
    [Column(Order = 11)]
    public DateTime? LastSyncedAt { get; set; }

    /// <summary>
    /// Video codec as reported by Plex (e.g. hevc, h264, vc1).
    /// </summary>
    [Column(Order = 12)]
    public required string VideoCodec { get; init; }

    /// <summary>
    /// Frame rate of the video stream.
    /// <example>24p, 30p, 60p</example>
    /// </summary>
    [Column(Order = 13)]
    public required string FrameRate { get; init; }

    /// <summary>
    /// Normalized resolution label derived from video height
    /// (480p / 720p / 1080p / 2160p).
    /// </summary>
    [Column(Order = 14)]
    public required string VideoResolution { get; init; }

    /// <summary>
    /// Derived release source (WEB-DL, Blu-ray, REMUX).
    /// Determined heuristically from file/container/bitrate.
    /// </summary>
    [Column(Order = 15)]
    public required ReleaseSource Source { get; init; }

    /// <summary>
    /// Best available audio codec for the release
    /// (e.g. TrueHD, DTS-HD MA, EAC3, AC3, AAC).
    /// </summary>
    [Column(Order = 16)]
    public required string AudioCodec { get; init; }

    /// <summary>
    /// Channel count of the primary audio track.
    /// </summary>
    [Column(Order = 17)]
    public required int? AudioChannels { get; init; }

    #region Relationships

    /// <summary>
    /// Identifier of the Plex library section this part belongs to.
    /// </summary>
    [Column(Order = 18)]
    public required int PlexLibraryId { get; set; }

    /// <summary>
    /// Identifier of the Plex server this part was synced from.
    /// </summary>
    [Column(Order = 19)]
    public required int PlexServerId { get; set; }

    /// <summary>
    /// Navigation property to the Plex library.
    /// </summary>
    [Column(Order = 20)]
    public PlexLibrary? PlexLibrary { get; init; }

    /// <summary>
    /// Navigation property to the Plex server.
    /// </summary>
    [Column(Order = 21)]
    public PlexServer? PlexServer { get; init; }

    #endregion

    #region Helpers

    public string GetFileName => !string.IsNullOrEmpty(GeneratedFilename) ? GeneratedFilename : OriginalFilename;

    #endregion
}
