using BencodeNET.Objects;
using BencodeNET.Torrents;
using FastEndpoints;
using FluentValidation;
using Microsoft.EntityFrameworkCore;
using Reaparr.Data.Contracts;

namespace Reaparr.PublicAPI;

public record DownloadTorrentEndpointRequest : TorrentMetadataDTO { }

public class DownloadTorrentEndpointRequestValidator : Validator<DownloadTorrentEndpointRequest>
{
    public DownloadTorrentEndpointRequestValidator()
    {
        RuleFor(x => x.DataId).GreaterThan(0);
        RuleFor(x => x.MediaId).GreaterThan(0);
        RuleFor(x => x.LibraryId).GreaterThan(0);
        RuleFor(x => x.ServerId).GreaterThan(0);
        RuleFor(x => x.Quality).IsInEnum();
        RuleFor(x => x.Type).IsInEnum();
        RuleFor(x => x)
            .Must(r => r.PartId > 0 || r.PartPlexId > 0)
            .WithMessage("Either PartId or PartPlexId must be provided.");
    }
}

public class DownloadTorrentEndpoint : Endpoint<DownloadTorrentEndpointRequest>
{
    private readonly IReaparrDbContext _dbContext;

    private const int PIECE_LENGTH = 256 * 1024; // 256KB

    private readonly ILogger _log;

    public DownloadTorrentEndpoint(ILogger logger, IReaparrDbContext dbContext)
    {
        _log = logger.ForContext<DownloadTorrentEndpoint>();
        _dbContext = dbContext;
    }

    public override void Configure()
    {
        Get(PublicApiRoutes.DownloadTorrent);
        Description(x => x.IsDownloadClient());

        Summary(x =>
        {
            x.Description =
                "Generates a minimal torrent file that will be used with Reaparr as a DownloadClient to trigger a download in Reaparr. This torrent cannot be used in normal DownloadClients!";
        });
        Description(x =>
            x.Produces(StatusCodes.Status200OK, contentType: "application/x-bittorrent")
                .Produces(StatusCodes.Status400BadRequest)
        );

        AllowAnonymous();
        PreProcessor<DownloadClientAuthenticationPreProcessor<DownloadTorrentEndpointRequest>>();
    }

    public override async Task HandleAsync(DownloadTorrentEndpointRequest req, CancellationToken ct)
    {
        _log.Here().DebugApiCall(HttpContext, req);

        // Create minimal torrent
        var fileInfo = await GetFileInfoAsync(req, ct);
        if (fileInfo is null)
        {
            _log.Here().Error("Could not find file info for {Type} with DataId {DataId}", req.Type, req.DataId);
            await Send.NotFoundAsync(ct);
            return;
        }

        var fileName = fileInfo.FileName + ".torrent";
        var numPieces = (int)Math.Ceiling((double)fileInfo.Size / PIECE_LENGTH);

        // Add extra fields to identify the torrent as a Reaparr status torrent and include metadata
        // that can later be used to trigger a Download command in Reaparr
        var extraFields = new BDictionary()
        {
            { "created by", "Reaparr" },
            { "comment", "Torrent generated by Reaparr - Cannot be used in normal DownloadClients!" },
        };

        foreach (var reqValue in req.Values)
            extraFields.Add(reqValue.Key, reqValue.Value);

        var torrent = new Torrent
        {
            CreationDate = DateTime.UtcNow,
            Pieces = new byte[numPieces * 20], // Empty pieces (20 bytes SHA1 hash each)
            PieceSize = PIECE_LENGTH,
            Trackers =
            [
                ["udp://tracker.opentrackr.org:1337/announce"],
            ],
            File = new SingleFileInfo { FileName = fileName, FileSize = fileInfo.Size },
            ExtraFields = extraFields,
        };

        // Return the torrent file
        await Send.BytesAsync(torrent.EncodeAsBytes(), fileName, "application/x-bittorrent", cancellation: ct);
    }

    private async Task<MediaFileInfo?> GetFileInfoAsync(DownloadTorrentEndpointRequest req, CancellationToken ct)
    {
        if (req.Type == PlexMediaType.Episode)
        {
            return await _dbContext
                .PlexTvShowEpisodeData.Where(x => x.Id == req.DataId)
                .SelectMany(x => x.Parts)
                .Where(p => p.Id == req.PartId || p.PlexId == req.PartPlexId)
                .Select(p => new MediaFileInfo { FileName = p.GeneratedFilename, Size = p.Size })
                .SingleOrDefaultAsync(ct);
        }

        if (req.Type == PlexMediaType.Movie)
        {
            return await _dbContext
                .PlexMovieData.Where(x => x.Id == req.DataId)
                .SelectMany(x => x.Parts)
                .Where(p => p.Id == req.PartId || p.PlexId == req.PartPlexId)
                .Select(p => new MediaFileInfo { FileName = p.GeneratedFilename, Size = p.Size })
                .SingleOrDefaultAsync(ct);
        }

        return null;
    }

    private record MediaFileInfo
    {
        public required string FileName { get; init; }

        public required long Size { get; init; }
    }
}
