using BencodeNET.Objects;
using BencodeNET.Torrents;
using FastEndpoints;
using FluentValidation;
using Microsoft.EntityFrameworkCore;
using Reaparr.Data.Contracts;

namespace Reaparr.PublicAPI;

public record DownloadTorrentEndpointRequest : TorrentMetadataDTO { }

public class DownloadTorrentEndpointRequestValidator : Validator<DownloadTorrentEndpointRequest>
{
    public DownloadTorrentEndpointRequestValidator()
    {
        RuleFor(x => x.DataId).GreaterThan(0);
        RuleFor(x => x.MediaId).GreaterThan(0);
        RuleFor(x => x.LibraryId).GreaterThan(0);
        RuleFor(x => x.ServerId).GreaterThan(0);
        RuleFor(x => x.Quality).IsInEnum();
        RuleFor(x => x.Type).IsInEnum();
    }
}

public class DownloadTorrentEndpoint : Endpoint<DownloadTorrentEndpointRequest>
{
    private readonly IReaparrDbContext _dbContext;

    private const int StatusPieceLength = 256 * 1024; // 256KB

    private readonly ILogger _log;

    public DownloadTorrentEndpoint(ILogger logger, IReaparrDbContext dbContext)
    {
        _log = logger.ForContext<DownloadTorrentEndpoint>();
        _dbContext = dbContext;
    }

    public override void Configure()
    {
        Get(PublicApiRoutes.DownloadTorrent);
        Description(x => x.IsDownloadClient());

        Summary(x =>
        {
            x.Description =
                "Generates a minimal torrent file that will be used with Reaparr as a DownloadClient to trigger a download in Reaparr. This torrent cannot be used in normal DownloadClients!";
        });
        Description(x => x
            .Produces(StatusCodes.Status200OK, contentType: "application/x-bittorrent")
            .Produces(StatusCodes.Status400BadRequest));
        
        AllowAnonymous();
        PreProcessor<DownloadClientAuthenticationPreProcessor<DownloadTorrentEndpointRequest>>();
    }

    public override async Task HandleAsync(DownloadTorrentEndpointRequest req, CancellationToken ct)
    {
        _log.Here().DebugApiCall(HttpContext, req);

        // Create minimal torrent
        var fileInfos = await GetFileNames(req);
        var fileInfo = fileInfos.FirstOrDefault();
        if (fileInfo is null)
        {
            _log.Here().Error("Could not find file info for {Type} with DataId {DataId}", req.Type, req.DataId);
            await Send.NotFoundAsync(ct);
            return;
        }

        var fileName = fileInfo.FileName + ".torrent";
        var numPieces = (int)Math.Ceiling((double)fileInfo.Size / StatusPieceLength);

        // Add extra fields to identify the torrent as a Reaparr status torrent and include metadata
        // that can later be used to trigger a Download command in Reaparr
        var extraFields = new BDictionary()
        {
            { "created by", "Reaparr" },
            { "comment", "Torrent generated by Reaparr - Cannot be used in normal DownloadClients!" },
        };

        foreach (var reqValue in req.Values)
            extraFields.Add(reqValue.Key, reqValue.Value);

        var torrent = new Torrent
        {
            CreationDate = DateTime.UtcNow,
            Pieces = new byte[numPieces * 20], // Empty pieces (20 bytes SHA1 hash each)
            PieceSize = StatusPieceLength,
            Trackers =
            [
                ["udp://tracker.opentrackr.org:1337/announce"],
            ],
            File = new SingleFileInfo
            {
                FileName = fileName,
                FileSize = fileInfo.Size,
            },
            ExtraFields = extraFields,
        };

        // Return the torrent file
        await Send.BytesAsync(
            torrent.EncodeAsBytes(),
            fileName,
            "application/x-bittorrent",
            cancellation: ct
        );
    }

    private async Task<List<MediaFileInfo>> GetFileNames(DownloadTorrentEndpointRequest req)
    {
        var fileNames = new List<MediaFileInfo>();
        if (req.Type == PlexMediaType.Episode)
        {
            fileNames = await _dbContext.PlexTvShowEpisodeData.Include(x => x.Parts)
                .Where(x => x.Id == req.DataId)
                .SelectMany(x => x.Parts)
                .Select(x => new MediaFileInfo
                {
                    FileName = Path.GetFileName(x.File),
                    Size = x.Size,
                })
                .ToListAsync();
        }

        if (req.Type == PlexMediaType.Movie)
        {
            fileNames = await _dbContext.PlexMovieData.Include(x => x.Parts)
                .Where(x => x.Id == req.DataId)
                .SelectMany(x => x.Parts)
                .Select(x => new MediaFileInfo
                {
                    FileName = Path.GetFileName(x.File),
                    Size = x.Size,
                })
                .ToListAsync();
        }

        return fileNames;
    }

    private record MediaFileInfo
    {
        public required string FileName { get; init; }

        public required long Size { get; init; }
    }
}