using BencodeNET.Objects;
using BencodeNET.Torrents;
using FastEndpoints;
using FluentValidation;

namespace Reaparr.PublicAPI;

public record DownloadTorrentEndpointRequest
{
    [QueryParam]
    public required Guid Guid { get; init; }
}

public class DownloadTorrentEndpointRequestValidator : Validator<DownloadTorrentEndpointRequest>
{
    public DownloadTorrentEndpointRequestValidator()
    {
        RuleFor(x => x.Guid).NotEmpty();
    }
}

public class DownloadTorrentEndpoint : Endpoint<DownloadTorrentEndpointRequest>
{
    private readonly ILogger _log;

    public DownloadTorrentEndpoint(ILogger logger)
    {
        _log = logger.ForContext<DownloadTorrentEndpoint>();
    }

    public override void Configure()
    {
        Get(PublicApiRoutes.DownloadTorrent);
        AllowAnonymous();
        Description(x => x
            .Produces(StatusCodes.Status200OK, contentType: "application/x-bittorrent")
            .Produces(StatusCodes.Status400BadRequest));
    }

    public override async Task HandleAsync(DownloadTorrentEndpointRequest req, CancellationToken ct)
    {
        _log.Here().DebugApiCall(HttpContext, req);

        // Create minimal torrent
        var fileName = Guid.NewGuid().ToString("N") + ".torrent";
        var fakeSize = 100 * 1024 * 1024; // 100MB placeholder
        var pieceLength = 256 * 1024;     // 256KB
        var numPieces = (int)Math.Ceiling((double)fakeSize / pieceLength);
        
        var torrent = new Torrent
        {
            CreationDate = DateTime.UtcNow,
            Pieces = new byte[numPieces * 20],
            PieceSize = pieceLength,
            Trackers =
            [
                ["udp://tracker.opentrackr.org:1337/announce"]
            ],
            File = new SingleFileInfo()
            {
                // Fake file reference - Sonarr/Radarr just needs a torrent that parses
                FileName = fileName,
                FileSize = fakeSize
            },
            ExtraFields = new BDictionary()
            {
                { "created by", "Reaparr" },
                { "comment", "Torrent generated by Reaparr" },
                { "reaparr-guid", req.Guid.ToString() },
            },
        };

        // Return the torrent file
        await Send.BytesAsync(
            torrent.EncodeAsBytes(),
            fileName,
            "application/x-bittorrent",
            cancellation: ct
        );
    }
}