<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Reaparr.PublicAPI.Contracts</AssemblyName>
        <RootNamespace>Reaparr.PublicAPI.Contracts</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
