<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Reaparr.PublicAPI.Contracts</AssemblyName>
        <RootNamespace>Reaparr.PublicAPI.Contracts</RootNamespace>
    </PropertyGroup>
</Project>
