<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Reaparr.Identity</AssemblyName>
        <RootNamespace>Reaparr.Identity</RootNamespace>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Data.Contracts\Data.Contracts.csproj" />
        <ProjectReference Include="..\Identity.Contracts\Identity.Contracts.csproj" />
        <ProjectReference Include="..\Logging\Logging.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.1.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FastEndpoints.Security" Version="7.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="_Shared\" />
    </ItemGroup>
</Project>
