name: 'Notify Discord of build status'
inputs:
    webhook:
        description: 'The Discord webhook URL.'
        required: true
    version:
        description: 'The version of the release.'
        required: true
    is-dev:
        description: 'Whether the release is a development release.'
        required: false
        default: 'false'
    changelog-url:
        description: 'The URL to the development changelog.'
        required: false
        default: ''

runs:
    using: 'composite'
    steps:
        -   name: Notify Discord of build status (Dev)
            if: ${{ inputs.is-dev == 'true' }}
            uses: sarisia/actions-status-discord@v1
            with:
                webhook: ${{ inputs.webhook }}
                nodetail: true
                title: "New Reaparr development version has been released!"
                color: "#0200ff" # Blue
                description: |
                    A new **development** version `${{ inputs.version }}` of Reaparr is now available on Docker!
                    [Development changelog](${{ inputs.changelog-url }})
                    Click [here](https://hub.docker.com/repository/docker/reaparr/reaparr/tags) to download the development version!
                username: PlexRipper
                url: ${{ inputs.changelog-url }}
                avatar_url: "https://raw.githubusercontent.com/Reaparr/Reaparr/refs/heads/dev/export/reaparr/logo/reaparr-full.svg"

        -   name: Notify Discord of build status (Stable)
            if: ${{ inputs.is-dev != 'true' }}
            uses: sarisia/actions-status-discord@v1
            with:
                webhook: ${{ inputs.webhook }}
                nodetail: true
                title: "New Reaparr version has been released!"
                color: "#ff0000" # Red
                description: |
                    A new **stable** version `${{ inputs.version }}` of Reaparr is now available on Docker!
                    [Release changelog](${{ inputs.changelog-url }})
                    Click [here](https://hub.docker.com/repository/docker/reaparr/reaparr/tags) to download the stable version!
                username: PlexRipper
                url: ${{ inputs.changelog-url }}
                avatar_url: "https://raw.githubusercontent.com/Reaparr/Reaparr/refs/heads/dev/export/reaparr/logo/reaparr-full.svg"
