import vueI18n from '@intlify/eslint-plugin-vue-i18n';
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt(
	...vueI18n.configs['flat/recommended'],
	{
		files: ['*.vue'],
		rules: {
			'vue/html-closing-bracket-newline': ['error', { multiline: 'never' }],
			// Reason: Opinionated not to have useless empty lines with just a closing tag
			'vue/component-name-in-template-casing': ['error', 'PascalCase',
				{ registeredComponentsOnly: false, ignores: quasarComponents() }],
			// Reason: This ensures that the order of components is always the same
			'vue/block-order': ['error', { order: ['template', 'script', 'style'] },
			],
		},
	},
	{
		rules: {
			'@intlify/vue-i18n/no-dynamic-keys': 'error',
			'@intlify/vue-i18n/no-unused-keys': [
				'error',
				{
					extensions: ['.js', '.vue'],
				},
			],
		},
		settings: {
			'vue-i18n': {
				localeDir: './src/lang/*.{json,json5,yaml,yml}',
				// Specify the version of `vue-i18n` you are using.
				// If not specified, the message will be parsed twice.
				messageSyntaxVersion: '^9.0.0',
			},
		},
	});

function quasarComponents() {
	return ['q-ajax-bar',
		'q-avatar',
		'q-badge',
		'q-alert',
		'q-layout',
		'q-header',
		'q-toolbar-title',
		'q-spinner-gears',
		'q-scroll',
		'q-page-container',
		'q-banner',
		'q-card-section',
		'q-bar',
		'q-breadcrumbs',
		'q-btn-toggle',
		'q-btn-dropdown',
		'q-button',
		'q-button-dropdown',
		'q-button-group',
		'q-card',
		'q-carousel',
		'q-chat-message',
		'q-checkbox',
		'q-chip',
		'q-circular-progress',
		'q-color-picker',
		'q-date',
		'q-dialog',
		'q-page',
		'q-editor',
		'q-expansion-item',
		'q-field',
		'q-file',
		'q-floating-action-button',
		'q-form',
		'q-icon',
		'q-img',
		'q-infinite-scroll',
		'q-inner-loading',
		'q-input',
		'q-intersection',
		'q-item',
		'q-item-section',
		'q-knob',
		'q-linear-progress',
		'q-list',
		'q-markup-table',
		'q-menu',
		'q-no-ssr',
		'q-option-group',
		'q-pagination',
		'q-parallax',
		'q-popup-edit',
		'q-popup-proxy',
		'q-pull-to-refresh',
		'q-radio',
		'q-range',
		'q-rating',
		'q-resize-observer',
		'q-responsive',
		'q-scroll-area',
		'q-scroll-observer',
		'q-select',
		'q-separator',
		'q-skeleton',
		'q-slide-item',
		'q-slider',
		'q-drawer',
		'q-item-label',
		'q-slide-transition',
		'q-space',
		'q-spinners',
		'q-splitter',
		'q-stepper',
		'q-table',
		'q-tab-panels',
		'q-tabs',
		'q-time',
		'q-timeline',
		'q-toggle',
		'q-tab',
		'q-btn',
		'q-tab-panel',
		'q-toolbar',
		'q-tooltip',
		'q-tree',
		'q-uploader',
		'q-video',
		'q-td',
		'q-tr',
		'q-virtual-scroll'];
}
