version: '3.4'
services:
    reaparr:
        container_name: Reaparr
        image: reaparr/reaparr:latest
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            # Web UI & Web API
            - '7000:7000'
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
            - LOG_LEVEL=INFORMATION # Set the logging level in the docker logging
            - LOG_ENV_VARS=false # Enable Log dump of all available ENV variables on Reaparr startup
            - UNMASKED=false # Unmask sensitive data in logs if true
        volumes:
            # The paths /mnt/TURBO/ReaparrDockerCache/ are examples, and you will need valid paths on your device with write permission.
            - /mnt/TURBO/ReaparrDockerCache/Config:/Config
            - /mnt/TURBO/ReaparrDockerCache/Downloads:/Downloads
            - /mnt/TURBO/ReaparrDockerCache/Movies:/Movies
            - /mnt/TURBO/ReaparrDockerCache/TvShows:/TvShows
