version: '3.4'
services:
    plexripper:
        container_name: PlexRipper
        image: plexripper/plexripper:latest
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        ports:
            # Web UI & Web API
            - '7000:7000'
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
            - LOG_LEVEL=INFORMATION # Set the logging level in the docker logging
            - LOG_ENV_VARS=false # Enable Log dump of all available ENV variables on PlexRipper startup
            - UNMASKED=false # Unmask sensitive data in logs if true
        volumes:
            # The paths /mnt/TURBO/PlexRipperDockerCache/ are examples, and you will need valid paths on your device with write permission.
            - /home/mfoust/PlexRipperDockerCache/Config:/Config
            - /home/mfoust/data/downloads:/Downloads
            - /home/mfoust/data/downloads:/Movies
            - /home/mfoust/data/downloads:/TvShows
