<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />
    <ItemGroup>
        <Using Include="System.ComponentModel.DataAnnotations" />
        <Using Include="System.ComponentModel.DataAnnotations.Schema" />
        <Using Include="FastEndpoints" />
        <Using Include="Reaparr.FluentResults" />
        <Using Include="Reaparr.FluentResultExtensions" />
        <Using Include="FluentValidation" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Reaparr.Domain" />
        <Using Include="Reaparr.Logging" />
        <Using Include="Serilog" />
    </ItemGroup>
</Project>
