//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    
    public class Activity
    {

        [JsonProperty("uuid")]
        public string? Uuid { get; set; }

        [JsonProperty("type")]
        public string? Type { get; set; }

        [JsonProperty("cancellable")]
        public bool? Cancellable { get; set; }

        [JsonProperty("userID")]
        public double? UserID { get; set; }

        [JsonProperty("title")]
        public string? Title { get; set; }

        [JsonProperty("subtitle")]
        public string? Subtitle { get; set; }

        [JsonProperty("progress")]
        public double? Progress { get; set; }

        [JsonProperty("Context")]
        public Context? Context { get; set; }
    }
}