//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Utils;
    
    /// <summary>
    /// Filters content by field and direction/equality<br/>
    /// 
    /// <remarks>
    /// (Unknown if viewedAt is the only supported column)<br/>
    /// 
    /// </remarks>
    /// </summary>
    public class Filter
    {
    }
}