//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Utils;
    
    /// <summary>
    /// Home Data
    /// </summary>
    public class GetHomeDataResponseBody
    {

        [JsonProperty("id")]
        public double? Id { get; set; }

        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("guestUserID")]
        public double? GuestUserID { get; set; }

        [JsonProperty("guestUserUUID")]
        public string? GuestUserUUID { get; set; }

        [JsonProperty("guestEnabled")]
        public bool? GuestEnabled { get; set; }

        [JsonProperty("subscription")]
        public bool? Subscription { get; set; }
    }
}