//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using OpenPlexAPI.Utils;

namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    
    public class GetLibraryItemsRequest
    {

        /// <summary>
        /// the Id of the library to query
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=sectionId")]
        public object SectionId { get; set; } = default!;

        /// <summary>
        /// A key representing a specific tag within the section.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=tag")]
        public Tag Tag { get; set; } = default!;

        /// <summary>
        /// Adds the Guids object to the response<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=includeGuids")]
        public long? IncludeGuids { get; set; }
    }
}