//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using NodaTime;
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    using System.Collections.Generic;
    
    public class GetLibraryItemsMetadata
    {

        [JsonProperty("ratingKey")]
        public string? RatingKey { get; set; }

        [JsonProperty("key")]
        public string? Key { get; set; }

        [JsonProperty("guid")]
        public string? Guid { get; set; }

        [JsonProperty("studio")]
        public string? Studio { get; set; }

        [JsonProperty("type")]
        public string? Type { get; set; }

        [JsonProperty("title")]
        public string? Title { get; set; }

        [JsonProperty("contentRating")]
        public string? ContentRating { get; set; }

        [JsonProperty("summary")]
        public string? Summary { get; set; }

        [JsonProperty("rating")]
        public double? Rating { get; set; }

        [JsonProperty("audienceRating")]
        public double? AudienceRating { get; set; }

        [JsonProperty("year")]
        public int? Year { get; set; }

        [JsonProperty("tagline")]
        public string? Tagline { get; set; }

        [JsonProperty("thumb")]
        public string? Thumb { get; set; }

        [JsonProperty("art")]
        public string? Art { get; set; }

        [JsonProperty("duration")]
        public int? Duration { get; set; }

        [JsonProperty("originallyAvailableAt")]
        public LocalDate? OriginallyAvailableAt { get; set; }

        [JsonProperty("addedAt")]
        public int? AddedAt { get; set; }

        [JsonProperty("updatedAt")]
        public int? UpdatedAt { get; set; }

        [JsonProperty("audienceRatingImage")]
        public string? AudienceRatingImage { get; set; }

        [JsonProperty("chapterSource")]
        public string? ChapterSource { get; set; }

        [JsonProperty("primaryExtraKey")]
        public string? PrimaryExtraKey { get; set; }

        [JsonProperty("ratingImage")]
        public string? RatingImage { get; set; }

        [JsonProperty("grandparentRatingKey")]
        public string? GrandparentRatingKey { get; set; }

        [JsonProperty("grandparentGuid")]
        public string? GrandparentGuid { get; set; }

        [JsonProperty("grandparentKey")]
        public string? GrandparentKey { get; set; }

        [JsonProperty("grandparentTitle")]
        public string? GrandparentTitle { get; set; }

        [JsonProperty("grandparentThumb")]
        public string? GrandparentThumb { get; set; }

        [JsonProperty("grandparentArt")]
        public string? GrandparentArt { get; set; }

        [JsonProperty("grandparentTheme")]
        public string? GrandparentTheme { get; set; }

        [JsonProperty("Media")]
        public List<GetLibraryItemsMedia>? Media { get; set; }

        [JsonProperty("Genre")]
        public List<GetLibraryItemsGenre>? Genre { get; set; }

        [JsonProperty("Country")]
        public List<GetLibraryItemsCountry>? Country { get; set; }

        [JsonProperty("Director")]
        public List<GetLibraryItemsDirector>? Director { get; set; }

        [JsonProperty("Writer")]
        public List<GetLibraryItemsWriter>? Writer { get; set; }

        [JsonProperty("Role")]
        public List<GetLibraryItemsRole>? Role { get; set; }

        [JsonProperty("titleSort")]
        public string? TitleSort { get; set; }

        [JsonProperty("viewCount")]
        public int? ViewCount { get; set; }

        [JsonProperty("lastViewedAt")]
        public int? LastViewedAt { get; set; }

        [JsonProperty("originalTitle")]
        public string? OriginalTitle { get; set; }

        [JsonProperty("viewOffset")]
        public int? ViewOffset { get; set; }

        [JsonProperty("skipCount")]
        public int? SkipCount { get; set; }

        [JsonProperty("index")]
        public int? Index { get; set; }

        [JsonProperty("theme")]
        public string? Theme { get; set; }

        [JsonProperty("leafCount")]
        public int? LeafCount { get; set; }

        [JsonProperty("viewedLeafCount")]
        public int? ViewedLeafCount { get; set; }

        [JsonProperty("childCount")]
        public int? ChildCount { get; set; }

        [JsonProperty("hasPremiumExtras")]
        public string? HasPremiumExtras { get; set; }

        [JsonProperty("hasPremiumPrimaryExtra")]
        public string? HasPremiumPrimaryExtra { get; set; }

        [JsonProperty("parentRatingKey")]
        public string? ParentRatingKey { get; set; }

        [JsonProperty("parentGuid")]
        public string? ParentGuid { get; set; }

        [JsonProperty("parentStudio")]
        public string? ParentStudio { get; set; }

        [JsonProperty("parentKey")]
        public string? ParentKey { get; set; }

        [JsonProperty("parentTitle")]
        public string? ParentTitle { get; set; }

        [JsonProperty("parentIndex")]
        public int? ParentIndex { get; set; }

        [JsonProperty("parentYear")]
        public int? ParentYear { get; set; }

        [JsonProperty("parentThumb")]
        public string? ParentThumb { get; set; }

        [JsonProperty("parentTheme")]
        public string? ParentTheme { get; set; }
    }
}