//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    
    /// <summary>
    /// The children of the library item.
    /// </summary>
    public class GetMetadataChildrenResponseBody
    {

        [JsonProperty("MediaContainer")]
        public GetMetadataChildrenMediaContainer? MediaContainer { get; set; }
    }
}