//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using OpenPlexAPI.Utils;

namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    
    public class GetPlaylistsRequest
    {

        /// <summary>
        /// limit to a type of playlist.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=playlistType")]
        public PlaylistType? PlaylistType { get; set; }

        /// <summary>
        /// type of playlists to return (default is all).
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=smart")]
        public QueryParamSmart? Smart { get; set; }
    }
}