//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    using System;
    
    /// <summary>
    /// The Pin
    /// </summary>
    public class GetPinResponseBody
    {

        /// <summary>
        /// PinID for use with authentication
        /// </summary>
        [JsonProperty("id")]
        public double? Id { get; set; }

        [JsonProperty("code")]
        public string? Code { get; set; }

        [JsonProperty("product")]
        public string? Product { get; set; }

        [JsonProperty("trusted")]
        public bool? Trusted { get; set; }

        /// <summary>
        /// a link to a QR code hosted on plex.tv <br/>
        /// 
        /// <remarks>
        /// The QR code redirects to the relevant `plex.tv/link` authentication page<br/>
        /// Which then prompts the user for the 4 Digit Link Pin<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("qr")]
        public string? Qr { get; set; }

        [JsonProperty("clientIdentifier")]
        public string? ClientIdentifier { get; set; }

        [JsonProperty("location")]
        public Location? Location { get; set; }

        [JsonProperty("expiresIn")]
        public double? ExpiresIn { get; set; }

        [JsonProperty("createdAt")]
        public DateTime? CreatedAt { get; set; }

        [JsonProperty("expiresAt")]
        public DateTime? ExpiresAt { get; set; }

        [JsonProperty("authToken")]
        public string? AuthToken { get; set; }

        [JsonProperty("newRegistration")]
        public bool? NewRegistration { get; set; } = null;
    }
}