//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using OpenPlexAPI.Utils;

namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Utils;
    
    public class GetPinRequest
    {

        /// <summary>
        /// Product name of the application shown in the list of devices<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Product")]
        public string XPlexProduct { get; set; } = default!;

        /// <summary>
        /// Determines the kind of code returned by the API call<br/>
        /// 
        /// <remarks>
        /// Strong codes are used for Pin authentication flows<br/>
        /// Non-Strong codes are used for `Plex.tv/link`<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=strong")]
        public bool? Strong { get; set; } = false;

        /// <summary>
        /// The unique identifier for the client application<br/>
        /// 
        /// <remarks>
        /// This is used to track the client application and its usage<br/>
        /// (UUID, serial number, or other number unique per device)<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Client-Identifier")]
        public string? XPlexClientIdentifier { get; set; }
    }
}