//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using OpenPlexAPI.Utils;

namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    
    public class GetResizedPhotoRequest
    {

        /// <summary>
        /// The width for the resized photo
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=width")]
        public double Width { get; set; } = default!;

        /// <summary>
        /// The height for the resized photo
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=height")]
        public double Height { get; set; } = default!;

        /// <summary>
        /// The opacity for the resized photo
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=opacity")]
        public long Opacity { get; set; } = 100;

        /// <summary>
        /// The width for the resized photo
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=blur")]
        public double Blur { get; set; } = default!;

        /// <summary>
        /// images are always scaled proportionally. A value of &apos;1&apos; in minSize will make the smaller native dimension the dimension resized against.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=minSize")]
        public MinSize MinSize { get; set; } = default!;

        /// <summary>
        /// allow images to be resized beyond native dimensions.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=upscale")]
        public Upscale Upscale { get; set; } = default!;

        /// <summary>
        /// path to image within Plex
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=url")]
        public string Url { get; set; } = default!;
    }
}