//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    using System.Collections.Generic;
    
    public class GetStatisticsMediaContainer
    {

        [JsonProperty("size")]
        public int? Size { get; set; }

        [JsonProperty("Device")]
        public List<GetStatisticsDevice>? Device { get; set; }

        [JsonProperty("Account")]
        public List<Account>? Account { get; set; }

        [JsonProperty("StatisticsMedia")]
        public List<StatisticsMedia>? StatisticsMedia { get; set; }
    }
}