//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using OpenPlexAPI.Utils;

namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Utils;
    
    public class GetTokenRequest
    {

        /// <summary>
        /// The PinID to retrieve an access token for
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=pinID")]
        public string PinID { get; set; } = default!;

        /// <summary>
        /// The unique identifier for the client application<br/>
        /// 
        /// <remarks>
        /// This is used to track the client application and its usage<br/>
        /// (UUID, serial number, or other number unique per device)<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Client-Identifier")]
        public string? XPlexClientIdentifier { get; set; }
    }
}