//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Models.Requests;
    using OpenPlexAPI.Utils;
    using System.Collections.Generic;
    
    public class GetUpdateStatusMediaContainer
    {

        [JsonProperty("size")]
        public int? Size { get; set; }

        [JsonProperty("canInstall")]
        public bool? CanInstall { get; set; }

        [JsonProperty("checkedAt")]
        public int? CheckedAt { get; set; }

        [JsonProperty("downloadURL")]
        public string? DownloadURL { get; set; }

        [JsonProperty("status")]
        public int? Status { get; set; }

        [JsonProperty("Release")]
        public List<Release>? Release { get; set; }
    }
}