//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Utils;
    
    /// <summary>
    /// Whether or not to include details for a section (types, filters, and sorts). <br/>
    /// 
    /// <remarks>
    /// Only exists for backwards compatibility, media providers other than the server libraries have it on always.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum IncludeDetails
    {
        Zero = 0,
        One = 1,
    }

}