//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Utils;
    
    public class Location
    {

        [JsonProperty("code")]
        public string? Code { get; set; }

        [JsonProperty("european_union_member")]
        public bool? EuropeanUnionMember { get; set; }

        [JsonProperty("continent_code")]
        public string? ContinentCode { get; set; }

        [JsonProperty("country")]
        public string? Country { get; set; }

        [JsonProperty("city")]
        public string? City { get; set; }

        [JsonProperty("time_zone")]
        public string? TimeZone { get; set; }

        [JsonProperty("postal_code")]
        public string? PostalCode { get; set; }

        [JsonProperty("in_privacy_restricted_country")]
        public bool? InPrivacyRestrictedCountry { get; set; }

        [JsonProperty("subdivisions")]
        public string? Subdivisions { get; set; }

        [JsonProperty("coordinates")]
        public string? Coordinates { get; set; }
    }
}