//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Utils;
    
    /// <summary>
    /// images are always scaled proportionally. A value of &apos;1&apos; in minSize will make the smaller native dimension the dimension resized against.
    /// </summary>
    public enum MinSize
    {
        Zero = 0,
        One = 1,
    }

}