//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Utils;
    
    /// <summary>
    /// type of playlists to return (default is all).
    /// </summary>
    public enum QueryParamSmart
    {
        Zero = 0,
        One = 1,
    }

}