//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Utils;
    
    public class Session
    {

        [JsonProperty("id")]
        public string? Id { get; set; }

        [JsonProperty("bandwidth")]
        public int? Bandwidth { get; set; }

        [JsonProperty("location")]
        public string? Location { get; set; }
    }
}