//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Utils;
    
    public class StatisticsResources
    {

        [JsonProperty("timespan")]
        public long? Timespan { get; set; }

        [JsonProperty("at")]
        public long? At { get; set; }

        [JsonProperty("hostCpuUtilization")]
        public float? HostCpuUtilization { get; set; }

        [JsonProperty("processCpuUtilization")]
        public float? ProcessCpuUtilization { get; set; }

        [JsonProperty("hostMemoryUtilization")]
        public float? HostMemoryUtilization { get; set; }

        [JsonProperty("processMemoryUtilization")]
        public float? ProcessMemoryUtilization { get; set; }
    }
}