//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using OpenPlexAPI.Utils;

namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Utils;
    
    public class StopTranscodeSessionRequest
    {

        /// <summary>
        /// the Key of the transcode session to stop
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=sessionKey")]
        public string SessionKey { get; set; } = default!;
    }
}