//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using OpenPlexAPI.Utils;

namespace OpenPlexAPI.Models.Requests
{
    using OpenPlexAPI.Utils;
    
    public class UpdatePlaylistRequest
    {

        /// <summary>
        /// the ID of the playlist
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=playlistID")]
        public double PlaylistID { get; set; } = default!;

        /// <summary>
        /// name of the playlist
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=title")]
        public string? Title { get; set; }

        /// <summary>
        /// summary description of the playlist
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=summary")]
        public string? Summary { get; set; }
    }
}