<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />
    <ItemGroup>
        <Using Include="Microsoft.AspNetCore.Builder" />
        <Using Include="Microsoft.AspNetCore.Hosting" />
        <Using Include="Microsoft.AspNetCore.Routing" />
        <Using Include="Microsoft.Extensions.Configuration" />
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="Microsoft.Extensions.Hosting" />
        <Using Include="Microsoft.Extensions.Logging" />
        <Using Include="System.Net.Http.Json" />
    </ItemGroup>
</Project>
