<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.Application.UnitTests</RootNamespace>
        <AssemblyName>Reaparr.Application.UnitTests</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="8.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CSharpier.MsBuild" Version="1.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.45.29" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Application\Application.csproj" />
        <ProjectReference Include="..\..\..\src\Environment\Environment.csproj" />
        <ProjectReference Include="..\..\..\src\FileSystem.Contracts\FileSystem.Contracts.csproj" />
        <ProjectReference Include="..\..\BaseTests\BaseTests.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Autofac" />
        <Using Include="Microsoft.EntityFrameworkCore" />
        <Using Include="Reaparr.Application.Contracts" />
        <Using Include="Reaparr.Data.Contracts" />
        <Using Include="Reaparr.Environment" />
        <Using Include="Reaparr.FileSystem.Contracts" />
        <Using Include="Reaparr.FluentResults" />
        <Using Include="Reaparr.FluentResultExtensions" />
        <Using Include="Reaparr.PublicAPI.Contracts" />
        <Using Include="Reaparr.PlexApi.Contracts" />
        <Using Include="Reaparr.Settings.Contracts" />
        <Using Include="Reaparr.SignalR.Contracts" />
        <Using Include="System.IO.Abstractions" />
        <Using Include="System.IO.Abstractions.TestingHelpers" />
        <Using Include="System.Reactive.Linq" />
        <Using Include="System.Text.Json" />
    </ItemGroup>
</Project>
