<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Reaparr.BaseTests</RootNamespace>
        <AssemblyName>Reaparr.BaseTests</AssemblyName>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" Version="8.4.0" />
        <PackageReference Include="Autofac.Extras.Moq" Version="7.0.0" />
        <PackageReference Include="Bogus" Version="35.6.3" />
        <PackageReference Include="Bogus.Hollywood" Version="35.6.3" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.1.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FastEndpoints.Testing" Version="7.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.8" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="Moq.Contrib.HttpClient" Version="1.4.0" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.0.15" />
        <PackageReference Include="xunit.v3" Version="3.0.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\AppHost\AppHost.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Update="xunit.runner.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\..\src\Domain\GlobalUsings.cs" />
    </ItemGroup>
</Project>
