<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Reaparr.BaseTests.Benchmarks</RootNamespace>
        <AssemblyName>Reaparr.BaseTests.Benchmarks</AssemblyName>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <OutputType>Exe</OutputType>
        <StartupObject>Reaparr.BaseTests.Benchmarks.ProgramBenchmarks</StartupObject>
        <GenerateProgramFile>false</GenerateProgramFile>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == ''">
        <Configuration>Release</Configuration>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <Optimize>true</Optimize>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <TieredCompilation>false</TieredCompilation>
        <Prefer32Bit>false</Prefer32Bit>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="BenchmarkDotNet.Diagnostics.dotTrace" Version="0.15.8" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\BaseTests\BaseTests.csproj" />
    </ItemGroup>
</Project>
