//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPlexAPI.Models.Errors
{
    using Newtonsoft.Json;
    using OpenPlexAPI.Models.Errors;
    using OpenPlexAPI.Utils;
    using System.Collections.Generic;
    using System.Net.Http;
    using System;
    
    /// <summary>
    /// X-Plex-Client-Identifier is missing
    /// </summary>
    public class GetPinResponseBody : Exception
    {

        [JsonProperty("errors")]
        public List<GetPinErrors>? Errors { get; set; }

        /// <summary>
        /// Raw HTTP response; suitable for custom response parsing
        /// </summary>
        [JsonProperty("-")]
        public HttpResponseMessage? RawResponse { get; set; }
    }
}