<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.FileSystem.Contracts</RootNamespace>
        <AssemblyName>Reaparr.FileSystem.Contracts</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.IO.Abstractions" Version="22.1.1" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Reaparr.Domain" />
    </ItemGroup>
</Project>
