<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="0.29.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.IO.Abstractions" Version="22.0.15" />
        <PackageReference Include="System.IO.FileSystem" Version="4.3.0"/>
    </ItemGroup>

</Project>
