#!/usr/bin/with-contenv bash

# Why this exists:
# - Some environments can end up with /Config created as root
#   before Reaparr writes ReaparrSettings.json, causing UnauthorizedAccessException.
# - We follow LinuxServer image practice by normalizing ownership at runtime using lsiown
#   before starting the app process as abc.
#
# Reference patterns used:
# - https://github.com/linuxserver/docker-sonarr/blob/master/root/etc/s6-overlay/s6-rc.d/init-sonarr-config/run
# - https://github.com/linuxserver/docker-radarr/blob/master/root/etc/s6-overlay/s6-rc.d/init-radarr-config/run
# - https://github.com/linuxserver/docker-plex/blob/master/root/etc/s6-overlay/s6-rc.d/init-plex-chown/run
# - https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/s6-overlay/s6-rc.d/init-adduser/run
#   (documents init-adduser defaults where unset PUID/PGID fall back to 911/911)
PORT=${PORT:-7000}

if [[ -z ${DOTNET_HTTP_PORTS} ]]; then
    DOTNET_HTTP_PORTS=${PORT}
    export DOTNET_HTTP_PORTS
fi

if [[ -z ${DOTNET_URLS} ]]; then
    DOTNET_URLS="http://+:${PORT}"
    export DOTNET_URLS
fi

exec s6-setuidgid abc dotnet /app/Reaparr.AppHost.dll