name: 'Client App Install'
description: 'Setup Bun and install dependencies'
runs:
    using: 'composite'
    steps:
        -   name: Setup Bun
            uses: oven-sh/setup-bun@v2
            with:
                # TODO: bun 1.2.1 breaks build so its pinned to this for now
                bun-version: "1.1.45"
        -   name: Clean install node_modules
            shell: bash
            run: bun install
            working-directory: src/AppHost/ClientApp/
