name: 'Client App Install'
description: 'Setup Bun and install dependencies'
runs:
    using: 'composite'
    steps:
        -   name: Setup Bun
            uses: oven-sh/setup-bun@v2
            with:
                bun-version: latest

        -   name: Cache Bun dependencies
            uses: actions/cache@v3
            with:
                path: ~/.bun/install/cache
                key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
                restore-keys: ${{ runner.os }}-bun-

        -   name: Clean install node_modules
            shell: bash
            run: bun install
            working-directory: src/AppHost/ClientApp/
