<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Reaparr.AppHost.UnitTests</RootNamespace>
        <AssemblyName>Reaparr.AppHost.UnitTests</AssemblyName>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="xunit.v3" Version="3.2.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog.Sinks.TestCorrelator" Version="4.0.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\BaseTests\BaseTests.csproj" />
        <ProjectReference Include="..\..\..\src\AppHost\AppHost.csproj" />
        <ProjectReference Include="..\BaseTests.UnitTests\BaseTests.UnitTests.csproj" />
    </ItemGroup>
</Project>
