<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.Application.Contracts</RootNamespace>
        <AssemblyName>Reaparr.Application.Contracts</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Quartz" Version="3.17.0" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="FastEndpoints" />
        <Using Include="FluentResults" />
        <Using Include="FluentValidation" />
        <Using Include="Quartz" />
        <Using Include="Reaparr.Domain" />
        <Using Include="Reaparr.FluentResultExtensions" />
        <Using Include="System.Text.Json.Serialization" />
    </ItemGroup>
</Project>
