<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Reaparr.BackgroundJobs.Contracts</RootNamespace>
        <AssemblyName>Reaparr.BackgroundJobs.Contracts</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Quartz" Version="3.15.0" />
    </ItemGroup>
</Project>
