<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <RootNamespace>Reaparr.PlexApi.Contracts</RootNamespace>
        <AssemblyName>Reaparr.PlexApi.Contracts</AssemblyName>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.1.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="LukeHagar.PlexAPI.SDK" Version="0.20.2" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Domain\GlobalUsings.cs">
            <Link>GlobalUsings.cs</Link>
        </Compile>
    </ItemGroup>
</Project>
