<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.PlexApi.Contracts</RootNamespace>
        <AssemblyName>Reaparr.PlexApi.Contracts</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="LukeHagar.PlexAPI.SDK" Version="0.20.7" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="System.ComponentModel.DataAnnotations" />
        <Using Include="System.ComponentModel.DataAnnotations.Schema" />
        <Using Include="FastEndpoints" />
        <Using Include="Reaparr.FluentResults" />
        <Using Include="FluentValidation" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Reaparr.Application.Contracts" />
        <Using Include="Reaparr.Domain" />
        <Using Include="Reaparr.Logging" />
        <Using Include="Serilog" />
    </ItemGroup>
</Project>
