<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.BackgroundJobs.UnitTests</RootNamespace>
        <AssemblyName>Reaparr.BackgroundJobs.UnitTests</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="8.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CSharpier.MsBuild" Version="1.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.45.29" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\BackgroundJobs\BackgroundJobs.csproj" />
        <ProjectReference Include="..\..\BaseTests\BaseTests.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Microsoft.EntityFrameworkCore" />
        <Using Include="Reaparr.BackgroundJobs.Contracts" />
    </ItemGroup>
</Project>
