<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.Environment.UnitTests</RootNamespace>
        <AssemblyName>Reaparr.Environment.UnitTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.45.29" />
        <PackageReference Include="coverlet.collector" Version="8.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Environment\Environment.csproj" />
        <ProjectReference Include="..\..\BaseTests\BaseTests.csproj" />
    </ItemGroup>
</Project>
