<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Reaparr.Data.Contracts</RootNamespace>
        <AssemblyName>Reaparr.Data.Contracts</AssemblyName>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.1.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="EFCore.BulkExtensions.SQLite" Version="9.0.1" />
        <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    </ItemGroup>
</Project>
