<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.Data.Contracts</RootNamespace>
        <AssemblyName>Reaparr.Data.Contracts</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="EFCore.BulkExtensions.SQLite" Version="10.0.1" />
        <PackageReference Include="FlexQuery.NET.EFCore" Version="2.3.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="FluentResults" />
        <Using Include="Microsoft.EntityFrameworkCore" />
        <Using Include="Reaparr.Application.Contracts" />
        <Using Include="Reaparr.Domain" />
        <Using Include="Reaparr.Logging" />
    </ItemGroup>
</Project>
