<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.Settings.UnitTests</RootNamespace>
        <AssemblyName>Reaparr.Settings.UnitTests</AssemblyName>
        <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.45.29" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Settings\Settings.csproj" />
        <ProjectReference Include="..\..\BaseTests\BaseTests.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Remove="MockData\ValidJsonSettings.json" />
    </ItemGroup>
</Project>
