<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Reaparr.Settings</AssemblyName>
        <RootNamespace>Reaparr.Settings</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.1.0" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\FileSystem.Contracts\FileSystem.Contracts.csproj" />
        <ProjectReference Include="..\Settings.Contracts\Settings.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup></ItemGroup>
</Project>
