<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Reaparr.Application</RootNamespace>
        <AssemblyName>Reaparr.Application</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Autofac.Extras.Quartz" Version="11.0.0" />
        <PackageReference Include="CSharpier.MsBuild" Version="1.2.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Downloader" Version="5.1.0" />
        <PackageReference Include="FastEndpoints" Version="8.1.0" />
        <PackageReference Include="FastEndpoints.Security" Version="8.1.0" />
        <PackageReference Include="FastEndpoints.Swagger" Version="8.1.0" />
        <PackageReference Include="Polly" Version="8.6.5" />
        <PackageReference Include="Polly.Core" Version="8.6.6" />
        <PackageReference Include="Quartz.Serialization.SystemTextJson" Version="3.17.0" />
        <PackageReference Include="Velopack" Version="0.0.1298" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
        <ProjectReference Include="..\BackgroundJobs.Contracts\BackgroundJobs.Contracts.csproj" />
        <ProjectReference Include="..\Data.Contracts\Data.Contracts.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\External.Contracts\External.Contracts.csproj" />
        <ProjectReference Include="..\FileSystem.Contracts\FileSystem.Contracts.csproj" />
        <ProjectReference Include="..\Identity.Contracts\Identity.Contracts.csproj" />
        <ProjectReference Include="..\PlexApi.Contracts\PlexApi.Contracts.csproj" />
        <ProjectReference Include="..\PublicAPI.Contracts\PublicAPI.Contracts.csproj" />
        <ProjectReference Include="..\Settings.Contracts\Settings.Contracts.csproj" />
        <ProjectReference Include="..\Settings\Settings.csproj" />
        <ProjectReference Include="..\SignalR.Contracts\SignalR.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Autofac" />
        <Using Include="System.ComponentModel.DataAnnotations" />
        <Using Include="System.ComponentModel.DataAnnotations.Schema" />
        <Using Include="System.ComponentModel" />
        <Using Include="System.Diagnostics" />
        <Using Include="System.Diagnostics.CodeAnalysis" />
        <Using Include="System.IO.Abstractions" />
        <Using Include="System.Text.Json" />
        <Using Include="System.Text.Json.Serialization" />
        <Using Include="FastEndpoints" />
        <Using Include="FluentResults" />
        <Using Include="FluentValidation" />
        <Using Include="Flurl" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.EntityFrameworkCore" />
        <Using Include="Quartz" />
        <Using Include="Reaparr.Application.Contracts" />
        <Using Include="Reaparr.Application.Contracts.Validators" />
        <Using Include="Reaparr.BackgroundJobs.Contracts" />
        <Using Include="Reaparr.Data.Contracts" />
        <Using Include="Reaparr.Domain" />
        <Using Include="Reaparr.Environment" />
        <Using Include="Reaparr.External.Contracts" />
        <Using Include="Reaparr.FileSystem.Contracts" />
        <Using Include="Reaparr.Identity.Contracts" />
        <Using Include="Reaparr.Logging" />
        <Using Include="Reaparr.PlexApi.Contracts" />
        <Using Include="Reaparr.PublicAPI.Contracts" />
        <Using Include="Reaparr.Settings" />
        <Using Include="Reaparr.Settings.Contracts" />
        <Using Include="Reaparr.SignalR.Contracts" />
        <Using Include="Serilog" />
        <Using Include="Velopack" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Reaparr.Application.UnitTests" />
    </ItemGroup>
</Project>
